### ISSUE TITLE
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_6:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_6". The following previous layers were accessed without issue: []

### ISSUE THREAD

**Issue by StudentRepresentative** [iamhimanshu0/Brain_Tumor_Classification#3]
I run your program in the google colab. I add one more layer in the code using resnet50. but i got the below error. why?
------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-280f8a2e9913> in <module>()
----> 1 model = Model(inputs = vgg.input,outputs=preds)
      2 model = Model(inputs = base_model.input,outputs=preds)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _map_graph_network(inputs, outputs)
   1819                              'The following previous layers '
   1820                              'were accessed without issue: ' +
-> 1821                              str(layers_with_complete_input))
   1822         for x in nest.flatten(node.output_tensors):
   1823           computable_tensors.add(x)

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_6:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_6". The following previous layers were accessed without issue: []

**Comment by iamhimanshu0** [comment]
Where u add more layer?

**Comment by StudentRepresentative** [comment]
Is this code is correct??
---------------------------------------------------------
import pandas as pd
import numpy as np
import os
import tensorflow as tf
import keras
import matplotlib.pyplot as plt
from keras.models import Sequential, Model
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

image_size = [224,224]
data_path = 'Data'

base_model =ResNet50(weights= 'imagenet', include_top=False, input_shape= image_size+[3])
vgg = VGG16(input_shape= image_size+[3],weights='imagenet',include_top=False)

vgg.output
base_model.output

x = vgg.output
x = base_model.output
x = GlobalAveragePooling2D()(x)

x = Dense(1024,activation='relu')(x)
x = Dense(1024,activation='relu')(x)
x = Dense(1024,activation='relu')(x)
x = Dense(512, activation='relu')(x)

preds = Dense(3,activation='softmax')(x)
model = Model(inputs = vgg.input,outputs=preds)           
model = Model(inputs = base_model.input,outputs=preds)

**Comment by iamhimanshu0** [comment]
Why u use two models ?  They both has some different way to implement that's why you got that error.. you just need to increase hidden layers ... And use only one model

**Comment by StudentRepresentative** [comment]
Yes ...I did that .....tq for your information.....
