### ISSUE TITLE
Even if i add more layers,it will show the wrong output.Why?

### ISSUE THREAD

**Issue by StudentRepresentative** [iamhimanshu0/Brain_Tumor_Classification#4]
[Brain_tumor.zip](https://github.com/iamhimanshu0/Brain_Tumor_Classification/files/4111751/Brain_tumor.zip)
Herewith i attached the edited code..With vgg16 i cant get correct output so here i tried the resnet50  model....Even if i add more layers i cant get correct output..Why?

**Comment by iamhimanshu0** [comment]
Try to increase data size or try to tune some parameter.

**Comment by StudentRepresentative** [comment]
Is this is possible to edit this code for detect the 3d brain tumor images like (BraTS dataset)
